name: Keep Vercel Backend Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Vercel backend
        run: curl -f https://saketh-ai-portfolio-be.vercel.app/health